const crase = [
    {
        question: 'No trecho "Sábio não é aquele que responde às perguntas, mas quem as coloca", o uso do acento indicativo de crase em "às perguntas" está corretamente justificado. Assinale a alternativa que explica a ocorrência da crase.', 
        a: 'A crase ocorre pela presença obrigatória do artigo definido feminino plural "as", independentemente da regência do verbo.', 
        b: 'A crase ocorre porque o substantivo "perguntas" está no plural e exige o uso do artigo definido feminino plural.', 
        c: 'A crase ocorre pela presença da preposição exigida pelo verbo "responde", mesmo que o substantivo "perguntas" não seja precedido de artigo.', 
        d: 'A crase ocorre pela fusão da preposição exigida pelo verbo "responde" com o artigo definido feminino plural "as", que acompanha o substantivo "perguntas".', 
        e: 'Nenhuma das alternativas acima.', 
        correct: 'D', 
        xp: 4,
        pontos: 3,
        int: 0.5,
        diff: 'F'
    },
    {
        question: 'Com base nas regras da ortografia oficial da Língua Portuguesa, analise as alternativas abaixo e assinale a opção correta quanto ao uso do termo "à toa" em "É uma ofensa se servir à toa. Cria-se na criança, desde cedo, uma consciência do tamanho do apetite", considerando sua classificação e emprego do acento indicativo de crase.', 
        a: 'A locução "à toa" está incorreta, já que o uso do acento grave foi abolido para locuções adverbiais no Acordo Ortográfico da Língua Portuguesa de 1990.', 
        b: 'A locução "à toa" está corretamente grafada, sendo obrigatória a crase por se tratar de uma locução adverbial feminina, formada pela fusão da preposição "a" com o artigo definido feminino "a".', 
        c: 'A locução "à toa" está corretamente grafada, mas o uso da crase é opcional, dependendo da interpretação do contexto em que aparece na frase.', 
        d: 'A locução "à toa" está incorreta, pois a crase não é necessária neste caso, uma vez que não há regência de preposição.', 
        e: 'Nenhuma das alternativas acima.', 
        correct: 'B', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '"Todos cuidam de todos, com um canto da mirada atenta às reações dos demais comensais."', 
        a: 'A crase foi empregada devido à presença de um termo masculino que, mesmo não exigindo o artigo definido, se combina com a preposição "a" por exigência do adjetivo.', 
        b: 'O uso da crase se justifica pela fusão da preposição exigida pelo adjetivo "atenta" e o artigo definido plural que acompanha o substantivo feminino "reações".', 
        c: 'A crase ocorre devido à regência verbal de "atenta", que exige preposição, e à presença do artigo definido feminino plural que acompanha "reações".', 
        d: 'A crase em "às reações" ocorre porque o adjetivo "atenta" rege a preposição "a", sendo esta obrigatória mesmo sem a presença do artigo definido feminino.', 
        e: 'Nenhuma das alternativas acima.', 
        correct: 'B', 
        xp: 2,
        pontos: 2,
        int: 0.2,
        diff: 'FF'
    },
    {
        question: 'Palestinos logo começaram a chegar "à região" de Detroit, em busca de novos empregos e altos salários. Em relação ao sinal indicativo de crase na expressão destacada, é correto afirmar que ela ocorre, de maneira: ', 
        a: 'obrigatória, devido à fusão da preposição "a" antecedente ao verbo "chegar" com o artigo feminino "a" que antecede o substantivo "região".', 
        b: 'facultativa, devido à fusão da preposição "a" antecedente ao verbo "chegar" com o artigo feminino "a" que antecede o substantivo "região".', 
        c: 'facultativa, devido à fusão da preposição "a" usada ou não posteriormente ao verbo "chegar" com o artigo feminino "a" que antecede o substantivo "região". ', 
        d: 'obrigatória, devido à fusão da preposição "a" exigida pelo verbo "chegar" com a preposição "a" que antecede o substantivo "região".', 
        e: 'obrigatória, devido à fusão da preposição "a" exigida posteriormente ao verbo "chegar" com o artigo feminino "a" que antecede o substantivo "região".', 
        correct: 'E', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    /*{
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },
    {
        question: '', 
        a: '', 
        b: '', 
        c: '', 
        d: '', 
        e: '', 
        correct: '', 
        xp: 5,
        pontos: 4,
        int: 0.6,
        diff: 'E'
    },*/
]

export default crase;